#!/bin/bash
inputfile=$1
tag=$2

## Function to extract the data required for the gantt diagram
function extract_gantt_data() {
marker_found=0

while read fline
do
    if [ ${marker_found} -eq 0 ]; then
        case $fline in
            =========*) marker_found=1 ;;
            *);;
        esac
    else
        echo $fline
    fi
done
}

if [ $# -lt 1 ]; then
    echo "usage: $0 <input_log_file> [tag]"
    exit 1
fi

if [ ! -f "$inputfile" ]; then
    echo "$inputfile does not exist"
    exit 2   
fi

if [ "$tag" == "" ]; then
    datafile=${inputfile%*.log}.csv
else
    datafile=${inputfile%*.log}_${tag}.csv
fi
target_file=${datafile%*.csv}.eps
target_gpfile=${datafile%*.csv}.gp


extract_gantt_data < $inputfile > $datafile

echo "Generating gantt chart..."
./gantt.py -o "${target_gpfile}" -c colors.cfg ${datafile}
echo "Generating EPS file..."
gnuplot -e "outfile='${target_file}'" -e "script='${target_gpfile}'" main.gp
echo "Done!"
rm -f ${target_gpfile} ${datafile}